# Template for setting up the Ubuntu build environment and building Xournal++ on
# Ubuntu

parameters:
  build_type: 'Debug'
  cmake_flags: ''
  cmake_commands: ''

steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install -y build-essential ninja-build cmake libgtk-3-dev libpoppler-glib-dev portaudio19-dev libsndfile-dev libcppunit-dev libxml2-dev liblua5.3-dev libzip-dev gettext

    displayName: 'Install dependencies'
